trigger: none
pr:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- template: templates/install-dependencies.yaml

# Scripts for running all tests in a file and to run tests based on test case name (integration testing)
- script: |
    robot \
    --variable    BROWSER:headlesschrome \
    --output-dir  results/logs/ \
    --xunit       output_miser_test_xunit.xml \
    --output      output_miser_test.xml \
    --log         log_miser_test.html \
    --report      report_miser_test.html \
    tests/miser.robot
  displayName: 'Run Test File "miser"'

- script: |
    robot \
    --variable    BROWSER:headlesschrome \
    --test "Add a Regular Adult ticket to cart" \
    --output-dir  results/logs/ \
    --xunit       output_pale_test_ticket_xunit.xml \
    --output      output_pale_test_ticket.xml \
    --log         log_pale_test_ticket.html \
    --report      report_pale_test_ticket.html \
    tests/
  displayName: 'Run Specific Test'

# Publish the Robot Framework reports as pipeline artifacts.
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/results/logs/'
    artifactName: 'robot-reports-develop'
  displayName: 'Publish Robot Framework Reports'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit' # 'JUnit' | 'NUnit' | 'VSTest' | 'XUnit' | 'CTest'. Alias: testRunner. Required. Test result format. Default: JUnit.
    testResultsFiles: 'results/logs/output_*_xunit.xml'
  displayName: 'Publish Robot Framework Test Results'
