trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: templates/install-dependencies.yaml

  # Scripts for running all tests in a file and to run tests based on test case name (integration testing)
  - script: |
      robot --output results/logs/output_miser_test.xml --log results/logs/log_miser_test.html --report results/logs/report_miser_test.html tests/miser.robot
    displayName: 'Run Test File "miser"'

  - script: |
      robot --test "Add a Regular Adult ticket to cart" --output results/logs/output_pale_test_ticket.xml --log results/logs/log_pale_test_ticket.html --report results/logs/report_pale_test_ticket.html tests/
    displayName: 'Run Specific Tests'

  # Publish the Robot Framework reports as pipeline artifacts.
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/results/logs/'
      artifactName: 'robot-reports-develop'
    displayName: 'Publish Robot Framework Reports'

